apiVersion: v1
kind: Service
metadata:
  labels:
    name: gateway
  name: gateway
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    name: gateway
