apiVersion: v1
kind: Service
metadata:
  labels:
    name: sale-service
  name: sale-service
spec:
  type: ClusterIP
  ports:
    - name: "8082"
      port: 8082
      targetPort: 8082
  selector:
    name: sale-service
