version: '3.7'

services:
  sale-service:
    depends_on:
      - zipkin
      - eureka
    image: docker/mmv2-sale:1.0.0
    ports:
      - "8082:8082"
    networks:
      - common-network
    environment:
      - EUREKA_HOST_NAME=eureka
      - ZIPKIN_HOST_NAME=zipkin

  admin-service:
    depends_on:
      - zipkin
      - eureka
    image: docker/mmv2-admin:1.0.0
    ports:
      - "8081:8081"
    networks:
      - common-network
    environment:
      - EUREKA_HOST_NAME=eureka
      - ZIPKIN_HOST_NAME=zipkin

  gateway:
    depends_on:
      - zipkin
      - eureka
      - sale-service
      - admin-service
    image: docker/mmv2-gateway:1.0.0
    ports:
      - "8080:8080"
    networks:
      - common-network
    environment:
      - EUREKA_HOST_NAME=eureka
      - ZIPKIN_HOST_NAME=zipkin

  eureka:
    image: docker/mmv2-eureka:1.0.0
    ports:
      - "8761:8761"
    networks:
      - common-network
    environment:
      - EUREKA_HOST_NAME=eureka
      - ZIPKIN_HOST_NAME=zipkin

  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"
    networks:
      - common-network
    environment:
      - EUREKA_HOST_NAME=eureka
      - ZIPKIN_HOST_NAME=zipkin

networks:
  common-network: