server:
  port: 8080
  host: localhost
  admin-url: /admin/v3/api-docs
  sale-url: /sale/v3/api-docs
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://${EUREKA_HOST_NAME:localhost}:8761/eureka}

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/admin/**
        - id: sale-service
          uri: lb://sale-service
          predicates:
            - Path=/sale/**

springdoc:
  api-docs:
    groups:
      enabled: true
    enabled: true
  group-configs:
    - group: admin-service
      paths-to-match: /admin/**/v3/api-docs
    - group: sale-service
      paths-to-match: /sale/**/v3/api-docs
  swagger-ui:
    config-url: /v3/api-docs/swagger-config
    url: /v3/api-docs
    urls:
      - url: ${server.admin-url}
        name: Admin
      - url: ${server.sale-url}
        name: Sale
    csrf:
      enabled: true

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://${ZIPKIN_HOST_NAME:localhost}:9411/api/v2/spans
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"