name: Admin

server:
  port: 8081
  servlet:
    context-path: /admin

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

spring:
  cloud:
    config:
      enabled: false

  application:
    name: admin-service
