apiVersion: v1
kind: Service
metadata:
  labels:
    name: zipkin
  name: zipkin
spec:
  type: LoadBalancer
  ports:
    - name: "9411"
      port: 9411
      targetPort: 9411
  selector:
    name: zipkin
