name: Sale

server:
  port: 8082
  servlet:
    context-path: /sale

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST_NAME:localhost}:8761/eureka/
  instance:
    prefer-ip-address: true

spring:
  cloud:
    config:
      enabled: false

  application:
    name: sale-service

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://${ZIPKIN_HOST_NAME:localhost}:9411/api/v2/spans
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

swagger:
  gateway-url: ${GATEWAY_URL:http://localhost:8080}${server.servlet.context-path}
  description: Sale service