name: Sale

server:
  port: 8082
  servlet:
    context-path: /sale

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST_NAME:localhost}:8761/eureka/
  instance:
    prefer-ip-address: true

spring:
  cloud:
    config:
      enabled: false

  application:
    name: sale-service

  datasource:
    url: jdbc:mysql://localhost:3306/sale
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#  cache:
#    type: redis
#    host: localhost
#    port: 6379
#    redis:
#      time-to-live: 60000
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
#      username: redisMyUsername
#      password: redisMyPassword
      timeout: 60000

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://${ZIPKIN_HOST_NAME:localhost}:9411/api/v2/spans
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    org:
      springframework:
        data:
          redis: DEBUG
        cache: DEBUG

swagger:
  gateway-url: ${GATEWAY_URL:http://localhost:8080}${server.servlet.context-path}
  description: Sale service