
version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql-server
    restart: always
    expose:
      - '3306'
    ports:
      - "3306:3306"
    volumes:
      - /path/to/local/d–∞ta:/root/redis
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root

