apiVersion: v1
kind: Service
metadata:
  labels:
    name: admin-service
  name: admin-service
spec:
  type: ClusterIP
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
  selector:
    name: admin-service
