apiVersion: v1
kind: Service
metadata:
  labels:
    name: eureka
  name: eureka
spec:
  type: ClusterIP
  ports:
    - name: "8761"
      port: 8761
      targetPort: 8761
  selector:
    name: eureka
