apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: sale-service
  name: sale-service
spec:
  replicas: 1
  selector:
    matchLabels:
      name: sale-service
  template:
    metadata:
      labels:
        name: sale-service
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: app-config-map
          image: <Aws_Account_ID>.dkr.ecr.us-east-1.amazonaws.com/sale:latest
          name: sale-service
          ports:
            - containerPort: 8082
              protocol: TCP
      restartPolicy: Always
